name: AppView
description: AppView module

version: 0.0.1



config:

    dependencies:

        App: latest

        Config: latest



config:

    default:

        AppView: # Конфиг модуля AeAppView

            views: ./node/views

            route: /
            paths:
                -
                    route: /
                    path: ./pub/assets
                -
                    route: /
                    path: ./pub/templates/Manage
