name: AppAuth
description: Authentication API

version: 0.1.1



config:

    dependencies:

        App: latest



dependencies:

    connect-redis: 1.4.6

    passport: 0.1.18
    passport-local: 0.1.6
