name: AppAuthenticationGithub
description: Githib Authentication API

version: 0.1.0



config:

    dependencies:

        AppAuth: latest



dependencies:

    passport-github: 0.1.5



config:

    default:

        auth:

            github:
                clientID: cc9377048ebeabf941cf
                clientSecret: 4b917b48ab0e2265802edb2b733c892833ad0a74
