name: Awesome
description: Awesome Api



config:

    dependencies:
        App: latest



dependencies:

    ware: 0.2.1

    connect-redis: 1.4.6

    passport: 0.1.18
    passport-local: 0.1.6
    passport-github: 0.1.5
