name: DbRedis
description: Redis Database Services

version: 0.1.0



config:

    dependencies:

        Db: latest



dependencies:

    redis: 0.10.0



config:

    default:

        db:

            redis:

                host: 127.0.0.1
                port: 6379

