name: apiserver
version: 0.3.1



config:

    logfile: './main.log'
    pidfile: './main.pid'

    console:
        port: 8002

    default:

        port: 8001

        db:

            maria:

                host: 127.0.0.1
                port: 3306

                database: jetcraft

                user: jetcraft
                password: jetcraft

                timezone: Z

                multipleStatements: true

                debug:
                    - ComQueryPacket

            redis:

                host: 127.0.0.1
                port: 6379

        sender:
            email:
                host: 'smtp.gmail.com'
                port: '465'
                secureConnection: true

                address: 'admin@google.com'
                password: 'password123'
                sign: 'oki'

            sms:
                id: 'id'
                key: 'key'
                from: 'from'

    development:

        installed: false

        db:

            maria:

                host: office.kd-eurotrans.com

                debug:
                    - ComQueryPacket

    production:

        installed: true

        db:

            maria:

                debug: false

    testing:

        installed: false

        db:

            maria:

                database: jetcraft_testing

                debug:
                    - ComQueryPacket



scripts:
    start: node index.js



dependencies:

    di: 0.0.1
    deferred: 0.6.6

    passport: 0.1.17
    passport-local: 0.1.6

    express: 3.4.3

    extend: 1.1.3

    connect-redis: 1.4.5
    redis: 0.8.4
    mysql: 2.0.0-alpha9

    log: 1.4.0
    request: 2.27.0
    nodemailer: 0.5.2



engines:
    node: ~0.10.20
