name: jet
version: 0.4.9



config:

    logfile: './main.log'



    path: ./node

    default:

        port: 8001




    development:

        installed: false



    testing:

        installed: false



    staging:

        installed: true



    production:

        installed: true



scripts:
    start: node --harmony index.js



dependencies:

    di: 0.0.1
    deferred: 0.6.8

    express: 3.4.8

    log: 1.4.0

    request: 2.33.0



engines:
    node: ~0.10.20
